//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAREABD1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficiario
    {
        public int Id { get; set; }
        public int NumeroCuenta { get; set; }
        public int ValorDocuIdentidadBeneficiario { get; set; }
        public int ParentezcoId { get; set; }
        public int Porcentaje { get; set; }
        public int Activo { get; set; }
    
        public virtual Parentezco Parentezco { get; set; }
    }
}
