//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAREABD1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public int Id { get; set; }
        public int ValorDocuIdentidadDelCliente { get; set; }
        public int TipoCuentaId { get; set; }
        public int NumeroCuenta { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string Saldo { get; set; }
    
        public virtual TipoCuentaAhorro TipoCuentaAhorro { get; set; }
    }
}
